version: '3'
services:
  flask:
    build: .
    container_name: flask
    expose:
      - "5000"
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"  # Change this line
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask

 
